<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{d7bd07a9-632a-4512-a44e-2ca193c0ff70}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	AxisControl : AxisControl;
	sizeMeasure : sizeMeasure;
	weightMeasure : WeightMeasure;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[AxisControl();
sizeMeasure();
weightMeasure();

//Size in cm
sizeMeasure.sizeInCm;

//Wweight in kg
weightMeasure.weightInKg;

//Breed calculation
BreedCalculation();

//Save new bin position
SaveNewBinPosition();

//Manual motion of servo
ServoManualMotion();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="23" Count="0" />
      <LineId Id="25" Count="0" />
      <LineId Id="24" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="32" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>