<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="PLC2Communicaton" Id="{9a88c0eb-c600-4a7f-b81d-78081ad1ee13}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PLC2Communicaton
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PLC2Communicaton">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>